Models/Address.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace netcoreapp.Models
{
    public class Address
    {
        public bool IsSelected { get; set; }
        public string MailingAddress { get; set; }
    }
}

Models/CreditCardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace netcoreapp.Models
{
    public class CreditCardViewModel
    {
        public CreditCardViewModel() { }
        public string CustomerName { get; set; }
        public string TotalAssets { get; set; }
        public string CustomerValue { get; set; }
        public string SolicitationPre { get; set; }
        public string AuthenticationLevel { get; set; }
        public string CardNumber { get; set; }
        public Address[] Addresses { get; set; }
        public bool IsExpeditedDelivery { get; set; }
        public string SelectedAddress { get; set; }
        public string DeliveryMethod { get; set; }

    }
}

Models/ErrorViewModel.cs
using System;

namespace netcoreapp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using netcoreapp.Models;

namespace netcoreapp.Controllers
{
    public class CardController : Controller
    {
        CreditCardViewModel model = new CreditCardViewModel
        {
            CardNumber = "Card 2 (...9754)",
            TotalAssets = "$2,252,898.00",
            CustomerValue = "Very High",
            SolicitationPre = "Phone and email OK",
            CustomerName = "Richard Gere",
            Addresses = new Address[]{ new Address{
                IsSelected=true,
                MailingAddress="101 Main St, Charlotte, NC 28262" },
               new Address{IsSelected=false,MailingAddress= "50 Croby St. New York, NY 10033 " }
            },
            DeliveryMethod="Standard"
        };
        public IActionResult Index()
        {
            return View(model);
        }

        public IActionResult BackToPrev()
        {
            return View();
        }

        public IActionResult Shipping()
        {
            model.SelectedAddress = model.Addresses.Where(x => x.IsSelected).FirstOrDefault().MailingAddress;
            return View(model);
        }

        public IActionResult Confirmation()
        {        
            return View(model);
        }

        public void Finish()
        {         
            //return View(model);
        }

    }
}

Controllers/CreditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using netcoreapp.Models;

namespace netcoreapp.Controllers
{
    public class CreditController : Controller
    {
      
        // GET: Credit
        public IActionResult Index()
        {
            var model = new CreditCardViewModel
            {
                CardNumber = "Test Credit Card",
                Addresses = new string[] { "Address1", "Address2" }
            };
            return View(model);
        }

        public IActionResult BackToPrev()
        {
            return View();
        }

        public IActionResult Shipping()
        {
            var model = new CreditCardViewModel
            {
                CardNumber = "Test Credit Card",
                Addresses = new string[] { "Address1", "Address2" }
            };
            return View(model);
        }

        public IActionResult Confirmation()
        {
            var model = new CreditCardViewModel
            {
                CardNumber = "Test Credit Card",
                Addresses = new string[] { "Address1", "Address2" }
            };
            return View(model);
        }

        public void Finish()
        {
            var model = new CreditCardViewModel
            {
                CardNumber = "Test Credit Card",
                Addresses = new string[] { "Address1", "Address2" }
            };
            //return View(model);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using netcoreapp.Models;

namespace netcoreapp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Card/BackToPrev.cshtml
@{
    ViewData["Title"] = "BackToPrev";
}

<h2>BackToPrev</h2>

Views/Card/Confirmation.cshtml
@model netcoreapp.Models.CreditCardViewModel
<h3>Summary</h3>
<div>
    Summary Section
</div>
<div>
    <h3>Replacement Card</h3>
    
    @Html.DisplayFor(model=>model.CardNumber)
</div>
<div>
    <h3>Shipping Address</h3>
    @Html.DisplayFor(model=>model.Addresses[0].MailingAddress)
</div>
<div>
    <h3>Delivery Method</h3>
    @Html.DisplayFor(model=>model.DeliveryMethod)
</div>
<div>
    <h3>Summary Communication</h3>
    Blah Blah
</div>
@Html.ActionLink("Back", "Shipping", "Card", null, new { @class = "btn btn-primary btn-large" })
<button onclick="finishProcess">Finish</button>
@Html.ActionLink("Continue", "Finish", "Card", null, new { @class = "btn btn-primary btn-large" })

<script type="text/javascript" defer="defer">
    var signedRequest = document.getElementById("<%= hdnSignedRequest.ClientID %>").value;
    alert(signedRequest);
    function finishProcess(pValue) {
        sr = JSON.parse(signedRequest);
        Sfdc.canvas.client.publish(sr.client, {
            name: 'myns.finished',
            payload: { value : pValue} });
    }
</script>

Views/Card/Index.cshtml
@model netcoreapp.Models.CreditCardViewModel
@{
    ViewData["Title"] = "Index";
}

<form method="post" action="/Card/Index">
    <br />
    <div class="row">
        <div class="col-md-2">
            <label>Customer</label>
        </div>

        <div class="col-md-2">
            <label>Total Assets</label>

        </div>
        <div class="col-md-2">
            <label>Solicitation Preference</label>

        </div>
        <div class="col-md-2">
            <label>Replacement Card</label>

        </div>
    </div>
    <div class="row">
        <div class="col-md-2">

            @Html.DisplayFor(x => x.CustomerName)
        </div>
        <div class="col-md-2">

            @Html.DisplayFor(x => x.TotalAssets)
        </div>
        <div class="col-md-2">

            @Html.DisplayFor(x => x.SolicitationPre)
        </div>
        <div class="col-md-2">

            @Html.DisplayFor(x => x.CardNumber)
        </div>
    </div>
    <h4>Although the customer will not receive their new card for several days, they will still have the ability to use their digital wallet.</h4>
    <h4>Confirm address for the shipping replacement card</h4>
    <br />
    @Html.DisplayFor(x => x.SelectedAddress)
    @foreach (var item in Model.Addresses)
    {       
        <div><label>@Html.RadioButtonFor(m => @item.MailingAddress, item.IsSelected)@item.MailingAddress</label></div>

    }
    <label>To Ship to an alternative address, enter a One time address</label>
    <br />
    @Html.ActionLink("Back", "BackToPrev", "Card", null, new { @class = "btn btn-primary btn-large" })
    @Html.ActionLink("Continue", "Shipping", "Card", null, new { @class = "btn btn-primary btn-large" })

</form>

Views/Card/Shipping.cshtml
@model netcoreapp.Models.CreditCardViewModel
<h3>Shipping</h3>
<div><label>@Html.RadioButtonFor(x=>x.DeliveryMethod, "Standard")Standard(Free)</label>
    Cards are delivered in 7-10 calendar days. The customer would receive their card by May 15th.
    Signature is not required. Shipping outside the united states may require additional 1-3 business days.
    </div>
<div>
    <label>@Html.RadioButtonFor(x => x.DeliveryMethod, "Expedited")Rush($16.00)</label>
    Cards are delivered in 1-2 business days. The customer would receive their card by May 4th.
    Signature is not required except for deliveries to the bank. Shipping outside the united states may require additional 1-3 business days.
</div>
@Html.ActionLink("Back", "Index", "Card", null, new { @class = "btn btn-primary btn-large" })
@Html.ActionLink("Continue", "Confirmation", "Card", null, new { @class = "btn btn-primary btn-large" })

Views/Credit/Confirmation.cshtml
@model netcoreapp.Models.CreditCardViewModel
<h3>Summary</h3>
<div>
    Summary Section
</div>
<div>
    <h3>Replacement Card</h3>
    
    @Html.DisplayFor(model=>model.CardNumber)
</div>
<div>
    <h3>Shipping Address</h3>
    @Html.DisplayFor(model=>model.Addresses[0])
</div>
<div>
    <h3>Delivery Method</h3>
    @Html.DisplayFor(model=>model.Addresses[0])
</div>
<div>
    <h3>Summary Communication</h3>
    Blah Blah
</div>
@Html.ActionLink("Back", "Shipping", "Credit", null, new { @class = "btn btn-primary btn-large" })
@Html.ActionLink("Continue", "Finish", "Credit", null, new { @class = "btn btn-primary btn-large" })

Views/Credit/Index.cshtml
@model netcoreapp.Models.CreditCardViewModel
@{
    ViewData["Title"] = "Index";
}



@using (Html.BeginForm("Index", "Credit", FormMethod.Post)){
    <h3>Although the customer will not receive their new card for several days, they will still have the ability to use their digital wallet.</h3>
    <br />
    <h3>Confirm address for the shipping replacement card</h3>
    <br />
    foreach (var item in Model.Addresses)
{

    <div><label>@Html.RadioButton("ABC", @item)@item</label></div>
   
}
    <label>To Ship to an alternative address, enter a One time address</label>
    <br />
    @Html.ActionLink("Back", "BackToPrev", "Credit", null, new { @class = "btn btn-primary btn-large" })
    @Html.ActionLink("Continue", "Shipping", "Credit", null, new { @class = "btn btn-primary btn-large" })

   
}

Views/Credit/Shipping.cshtml
@model netcoreapp.Models.CreditCardViewModel
<h3>Shipping</h3>
<div><label>@Html.RadioButton("ABC", "")Standard(Free)</label>
    Cards are delivered in 7-10 calendar days. The customer would receive their card by May 15th.
    Signature is not required. Shipping outside the united states may require additional 1-3 business days.
    </div>
<div>
    <label>@Html.RadioButton("ABC", "")Rush($16.00)</label>
    Cards are delivered in 1-2 business days. The customer would receive their card by May 4th.
    Signature is not required except for deliveries to the bank. Shipping outside the united states may require additional 1-3 business days.
</div>
@Html.ActionLink("Back", "Index", "Credit", null, new { @class = "btn btn-primary btn-large" })
@Html.ActionLink("Continue", "Confirmation", "Credit", null, new { @class = "btn btn-primary btn-large" })

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - netcoreapp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>   
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">netcoreapp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - netcoreapp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/canvas-all.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/canvas-all.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>